"""initial schema

Revision ID: 216f3377adf5
Revises: 
Create Date: 2026-07-06 23:21:44.493349+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216f3377adf5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_type'), ['type'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_api_key'), ['api_key'], unique=True)

    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('spiffe_id', sa.String(), nullable=True),
    sa.Column('selectors', sa.JSON(), nullable=False),
    sa.Column('biscuit', sa.Text(), nullable=True),
    sa.Column('biscuit_kid', sa.String(), nullable=True),
    sa.Column('biscuit_revocation_ids', sa.JSON(), nullable=False),
    sa.Column('bound_keyhash', sa.String(), nullable=True),
    sa.Column('workload_pubkey_pem', sa.Text(), nullable=True),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_spiffe_id'), ['spiffe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_status'), ['status'], unique=False)

    op.create_table('attestation_uses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'jti', name='uq_attestation_use')
    )
    with op.batch_alter_table('attestation_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attestation_uses_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attestation_uses_jti'), ['jti'], unique=False)

    op.create_table('biscuit_revocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('revocation_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'revocation_id', name='uq_biscuit_revocation')
    )
    with op.batch_alter_table('biscuit_revocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biscuit_revocations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biscuit_revocations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_biscuit_revocations_revocation_id'), ['revocation_id'], unique=False)

    op.create_table('biscuit_root_keys',
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('private_hex', sa.Text(), nullable=False),
    sa.Column('public_hex', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('kid')
    )
    with op.batch_alter_table('biscuit_root_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biscuit_root_keys_customer_id'), ['customer_id'], unique=False)

    op.create_table('capability_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capability_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_challenges_challenge'), ['challenge'], unique=True)
        batch_op.create_index(batch_op.f('ix_capability_challenges_customer_id'), ['customer_id'], unique=False)

    op.create_table('node_attestors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_attestors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_attestors_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_node_attestors_type'), ['type'], unique=False)

    op.create_table('registration_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('selectors', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_entries_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_entries_customer_id'), ['customer_id'], unique=False)

    op.create_table('signing_keys',
    sa.Column('kid', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('private_pem', sa.Text(), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('kid')
    )
    with op.batch_alter_table('signing_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signing_keys_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signing_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signing_keys_customer_id'))

    op.drop_table('signing_keys')
    with op.batch_alter_table('registration_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_entries_customer_id'))
        batch_op.drop_index(batch_op.f('ix_registration_entries_agent_type'))

    op.drop_table('registration_entries')
    with op.batch_alter_table('node_attestors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_attestors_type'))
        batch_op.drop_index(batch_op.f('ix_node_attestors_customer_id'))

    op.drop_table('node_attestors')
    with op.batch_alter_table('capability_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_challenges_customer_id'))
        batch_op.drop_index(batch_op.f('ix_capability_challenges_challenge'))

    op.drop_table('capability_challenges')
    with op.batch_alter_table('biscuit_root_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biscuit_root_keys_customer_id'))

    op.drop_table('biscuit_root_keys')
    with op.batch_alter_table('biscuit_revocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biscuit_revocations_revocation_id'))
        batch_op.drop_index(batch_op.f('ix_biscuit_revocations_customer_id'))
        batch_op.drop_index(batch_op.f('ix_biscuit_revocations_agent_id'))

    op.drop_table('biscuit_revocations')
    with op.batch_alter_table('attestation_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attestation_uses_jti'))
        batch_op.drop_index(batch_op.f('ix_attestation_uses_customer_id'))

    op.drop_table('attestation_uses')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_status'))
        batch_op.drop_index(batch_op.f('ix_agents_spiffe_id'))
        batch_op.drop_index(batch_op.f('ix_agents_owner'))
        batch_op.drop_index(batch_op.f('ix_agents_jti'))
        batch_op.drop_index(batch_op.f('ix_agents_customer_id'))
        batch_op.drop_index(batch_op.f('ix_agents_agent_type'))

    op.drop_table('agents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_api_key'))

    op.drop_table('customers')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_customer_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
